# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downloader.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
class QLabelClickable(QLabel):
    clicked = pyqtSignal(str)
    
    def __init__(self, parent=None):
        super(QLabelClickable, self).__init__(parent)

    def mousePressEvent(self, event):
        self.ultimo = "Clic"
    
    def mouseReleaseEvent(self, event):
        if self.ultimo == "Clic":
            QTimer.singleShot(QApplication.instance().doubleClickInterval(),
                              self.performSingleClickAction)
        else:
            # Realizar acción de doble clic.
            self.clicked.emit(self.ultimo)
    
    def mouseDoubleClickEvent(self, event):
        self.ultimo = "Doble Clic"
    
    def performSingleClickAction(self):
        if self.ultimo == "Clic":
            self.clicked.emit(self.ultimo)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(796, 518)
        Form.setStyleSheet("QScrollBar:vertical\n"
"{\n"
"border:none;\n"
"background:rgb(56, 58, 89);\n"
"margin: 15px 0px 15px 0;\n"
"width:15px;\n"
"border-radius:0px;\n"
"}\n"
"QScrollBar::handle:vertical\n"
"{\n"
"background:rgb(84, 88, 134);\n"
"border-radius:7px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    background-color: rgb(255, 0, 255);\n"
"}\n"
"QScrollBar::handle:vertical:pressed\n"
"{\n"
"    background-color: rgb(255, 119, 253);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical\n"
"{\n"
"border:none;\n"
"height:15px;\n"
"background-color: rgb(37, 39, 59);\n"
"border-top-left-radius:7px;\n"
"border-top-right-radius:7px;\n"
"subcontrol-position:top;\n"
"subcontrol-origin:margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:hover\n"
"{\n"
"background-color: rgb(255, 0, 255);\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical:pressed\n"
"{\n"
"background-color: rgb(255, 119, 253)\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical\n"
"{\n"
"border:none;\n"
"\n"
"background-color: rgb(37, 39, 59);\n"
"border-bottom-left-radius:7px;\n"
"border-bottom-right-radius:7px;\n"
"height:15px;\n"
"subcontrol-position:bottom;\n"
"subcontrol-origin:margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical:hover\n"
"{\n"
"background-color: rgb(255, 0, 255);\n"
"}\n"
"QScrollBar::add-line:vertical:pressed\n"
"{\n"
"background-color: rgb(255, 119, 253)\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical\n"
"{\n"
"background:none;\n"
"}\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical\n"
"{\n"
"background:none;\n"
"}\n"
"\n"
"\n"
"QScrollBar:horizontal\n"
"{\n"
"border:none;\n"
"background:rgb(56, 58, 89);\n"
"margin: 0 15px 0 15px;\n"
"height:15px;\n"
"border-radius:0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal\n"
"{\n"
"background:rgb(84, 88, 134);\n"
"border-radius:7px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover\n"
"{\n"
"    background-color: rgb(255, 0, 255);\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:pressed\n"
"{\n"
"    background-color: rgb(255, 119, 253);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal\n"
"{\n"
"border:none;\n"
"width:15px;\n"
"background-color: rgb(37, 39, 59);\n"
"border-top-left-radius:7px;\n"
"border-bottom-left-radius:7px;\n"
"subcontrol-position:left;\n"
"subcontrol-origin:margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:hover\n"
"{\n"
"background-color: rgb(255, 0, 255);\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal:pressed\n"
"{\n"
"background-color: rgb(255, 119, 253)\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal\n"
"{\n"
"border:none;\n"
"background-color: rgb(37, 39, 59);\n"
"border-top-right-radius:7px;\n"
"border-bottom-right-radius:7px;\n"
"width:15px;\n"
"subcontrol-position:right;\n"
"subcontrol-origin:margin;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal:hover\n"
"{\n"
"background-color: rgb(255, 0, 255);\n"
"}\n"
"QScrollBar::add-line:horizontal:pressed\n"
"{\n"
"background-color: rgb(255, 119, 253)\n"
"}\n"
"\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"background:none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"background:none;\n"
"}\n"
"")
        self.mainFrame = QtWidgets.QFrame(Form)
        self.mainFrame.setGeometry(QtCore.QRect(0, 0, 801, 521))
        self.mainFrame.setStyleSheet("QFrame#mainFrame\n"
"{\n"
"background:rgb(0, 0, 23);\n"
"border-radius:8px;\n"
"}\n"
"\n"
"QPushButton#quitButton\n"
"{\n"
"background:rgb(0, 0, 23);\n"
"color:white;\n"
"font: 10pt \"Palatino Linotype\";\n"
"}\n"
"QPushButton#quitButton:hover{\n"
"background:rgb(255, 0, 15);\n"
"}\n"
"QPushButton\n"
"{\n"
"border:none;\n"
"}\n"
"QLabel\n"
"{\n"
"color:white;\n"
"}\n"
"QScrollBar:vertical\n"
"{\n"
"    \n"
"    background-color: rgb(85, 255, 255);\n"
"}\n"
"\n"
"QPushButton#playButton\n"
"{\n"
"background: rgb(192, 44, 241);\n"
"font: 63 16pt \"Roboto Slab SemiBold\";\n"
"color:black;\n"
"border:none;\n"
"border-radius:8px;\n"
"}\n"
"QPushButton#playButton:hover\n"
"{\n"
"background:rgb(255, 35, 252);\n"
"}\n"
"\n"
"")
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.quitFrame = QtWidgets.QFrame(self.mainFrame)
        self.quitFrame.setGeometry(QtCore.QRect(0, 0, 801, 31))
        self.quitFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.quitFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.quitFrame.setObjectName("quitFrame")
        self.quitButton = QtWidgets.QPushButton(self.quitFrame)
        self.quitButton.setGeometry(QtCore.QRect(753, 0, 41, 31))
        self.quitButton.setObjectName("quitButton")
        self.stackedWidget = QtWidgets.QStackedWidget(self.mainFrame)
        self.stackedWidget.setGeometry(QtCore.QRect(50, 30, 751, 491))
        self.stackedWidget.setStyleSheet("QWidget\n"
"{\n"
"background:rgb(56, 58, 89);\n"
"}\n"
"QLineEdit#home_search_line_edit\n"
"{\n"
"border-radius:3px;\n"
"font: 11pt \"Roboto\";\n"
"border: 1px solid white;\n"
"color:white;\n"
"}\n"
"QLineEdit#home_search_line_edit:hover\n"
"{\n"
"background:rgb(81, 84, 129);\n"
"}\n"
"QPushButton#home_download_button\n"
"{\n"
"background:rgb(192, 44, 241);\n"
"font: 63 16pt \"Roboto Slab SemiBold\";\n"
"color:black;\n"
"border:none;\n"
"border-radius:8px;\n"
"}\n"
"QPushButton#home_download_button:hover\n"
"{\n"
"background:rgb(255, 35, 252);\n"
"}\n"
"")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home_page = QtWidgets.QWidget()
        self.home_page.setObjectName("home_page")
        self.home_search_line_edit = QtWidgets.QLineEdit(self.home_page)
        self.home_search_line_edit.setGeometry(QtCore.QRect(10, 30, 721, 51))
        self.home_search_line_edit.setObjectName("home_search_line_edit")
        self.home_download_button = QtWidgets.QPushButton(self.home_page)
        self.home_download_button.setGeometry(QtCore.QRect(500, 440, 231, 41))
        self.home_download_button.setStyleSheet("")
        self.home_download_button.setObjectName("home_download_button")
        self.home_list_edit = QtWidgets.QListWidget(self.home_page)
        self.home_list_edit.setGeometry(QtCore.QRect(10, 90, 721, 341))
        self.home_list_edit.setStyleSheet("QListWidget\n"
"{color:white;\n"
"font: 63 12pt \"Roboto Slab SemiBold\";\n"
"border:none;\n"
"}\n"
"")
        self.home_list_edit.setObjectName("home_list_edit")
        self.stackedWidget.addWidget(self.home_page)
        self.downloads_page = QtWidgets.QWidget()
        self.downloads_page.setObjectName("downloads_page")
        self.downloads_downloads_list_widget = QtWidgets.QListWidget(self.downloads_page)
        self.downloads_downloads_list_widget.setGeometry(QtCore.QRect(0, 0, 741, 411))
        self.downloads_downloads_list_widget.setStyleSheet("QListWidget\n"
"{color:white;\n"
"font: 63 12pt \"Roboto Slab SemiBold\";\n"
"border:none;\n"
"}\n"
"")
        self.downloads_downloads_list_widget.setObjectName("downloads_downloads_list_widget")
        self.downloads_open_button = QtWidgets.QPushButton(self.downloads_page)
        self.downloads_open_button.setGeometry(QtCore.QRect(480, 435, 181, 41))
        self.downloads_open_button.setStyleSheet("QPushButton\n"
"{\n"
"background:rgb(192, 44, 241);\n"
"font: 63 14pt \"Roboto Slab SemiBold\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background:rgb(255, 35, 252);\n"
"}\n"
"")
        self.downloads_open_button.setObjectName("downloads_open_button")
        self.downloads_search_downloads_line_edit = QtWidgets.QLineEdit(self.downloads_page)
        self.downloads_search_downloads_line_edit.setGeometry(QtCore.QRect(20, 435, 431, 41))
        self.downloads_search_downloads_line_edit.setStyleSheet("QLineEdit\n"
"{\n"
"border:none;\n"
"border-bottom: 3px solid qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"font: 63 16pt \"Roboto Slab SemiBold\";\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"border-bottom: 5px solid qconicalgradient(cx:0, cy:0, angle:135, stop:0 rgba(255, 255, 0, 69), stop:0.375 rgba(255, 255, 0, 69), stop:0.423533 rgba(251, 255, 0, 145), stop:0.45 rgba(247, 255, 0, 208), stop:0.477581 rgba(255, 244, 71, 130), stop:0.518717 rgba(255, 218, 71, 130), stop:0.55 rgba(255, 255, 0, 255), stop:0.57754 rgba(255, 203, 0, 130), stop:0.625 rgba(255, 255, 0, 69), stop:1 rgba(255, 255, 0, 69));\n"
"}")
        self.downloads_search_downloads_line_edit.setObjectName("downloads_search_downloads_line_edit")
        self.stackedWidget.addWidget(self.downloads_page)
        self.mp3_page = QtWidgets.QWidget()
        self.mp3_page.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(56, 58, 89);\n"
"    color: white;\n"
"    border:1px solid qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"    font: 87 14pt \"Roboto Slab Black\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(114, 118, 180);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    \n"
"    background-color: rgb(133, 13, 141);\n"
"}\n"
"QLineEdit\n"
"{\n"
"    font: 81 16pt \"Raleway ExtraBold\";\n"
"}")
        self.mp3_page.setObjectName("mp3_page")
        self.mp3_file_location_line_edit = QtWidgets.QLineEdit(self.mp3_page)
        self.mp3_file_location_line_edit.setGeometry(QtCore.QRect(10, 30, 661, 41))
        self.mp3_file_location_line_edit.setObjectName("mp3_file_location_line_edit")
        self.mp3_save_location_line_edit = QtWidgets.QLineEdit(self.mp3_page)
        self.mp3_save_location_line_edit.setGeometry(QtCore.QRect(10, 80, 661, 41))
        self.mp3_save_location_line_edit.setObjectName("mp3_save_location_line_edit")
        self.convert_button = QtWidgets.QPushButton(self.mp3_page)
        self.convert_button.setGeometry(QtCore.QRect(10, 140, 261, 41))
        self.convert_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color:rgb(215, 52, 255);\n"
"    \n"
"    font: 63 16pt \"Roboto Slab SemiBold\";\n"
"border: 3px solid qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(245, 224, 176,     255), stop:0.09 rgba(246, 189, 237, 255), stop:0.14 rgba(194, 207, 246, 255), stop:0.19 rgba(184,     160, 168, 255), stop:0.25 rgba(171, 186, 248, 255), stop:0.32 rgba(243, 248, 224, 255), stop:0.385     rgba(249, 162, 183, 255), stop:0.47 rgba(100, 115, 124, 255), stop:0.58 rgba(251, 205, 202, 255), stop:0.65 rgba(170, 128, 185, 255), stop:0.75 rgba(252, 222, 204, 255), stop:0.805 rgba(206, 122, 218, 255), stop:0.86 rgba(254, 223, 175, 255), stop:0.91 rgba(254, 236, 244, 255), stop:1 rgba(255, 191, 221, 255));\n"
"border-radius:20px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(234, 129, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color: rgb(183, 44, 217);\n"
"}")
        self.convert_button.setObjectName("convert_button")
        self.mp3_file_location_browse_button = QtWidgets.QPushButton(self.mp3_page)
        self.mp3_file_location_browse_button.setGeometry(QtCore.QRect(680, 30, 61, 41))
        self.mp3_file_location_browse_button.setObjectName("mp3_file_location_browse_button")
        self.mp3_save_location_browse_button = QtWidgets.QPushButton(self.mp3_page)
        self.mp3_save_location_browse_button.setGeometry(QtCore.QRect(680, 80, 61, 41))
        self.mp3_save_location_browse_button.setObjectName("mp3_save_location_browse_button")
        self.progressBar = QtWidgets.QProgressBar(self.mp3_page)
        self.progressBar.setGeometry(QtCore.QRect(10, 200, 721, 31))
        self.progressBar.setStyleSheet("QProgressBar\n"
"{\n"
"background-color:rgb(134, 139, 212);\n"
"border-style:none;\n"
"text-align:center;\n"
"border-radius:10px;\n"
"}\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.494318, x2:1, y2:0.522727, stop:0.170455 rgba(255, 194, 203, 255), stop:1 rgba(170, 85, 255, 255));\n"
"border-radius:10px;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.mp3s_list_widget = QtWidgets.QListWidget(self.mp3_page)
        self.mp3s_list_widget.setGeometry(QtCore.QRect(10, 260, 431, 201))
        self.mp3s_list_widget.setStyleSheet("font: 16pt \"Segoe UI Historic\";\n"
"color:white;\n"
"border:none;")
        self.mp3s_list_widget.setObjectName("mp3s_list_widget")
        self.mp3_play_button = QtWidgets.QPushButton(self.mp3_page)
        self.mp3_play_button.setGeometry(QtCore.QRect(520, 300, 141, 41))
        self.mp3_play_button.setStyleSheet("QPushButton\n"
"{\n"
"border:4px solid qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border:10px solid qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"}")
        self.mp3_play_button.setObjectName("mp3_play_button")
        self.mp3_open_button = QtWidgets.QPushButton(self.mp3_page)
        self.mp3_open_button.setGeometry(QtCore.QRect(520, 400, 141, 41))
        self.mp3_open_button.setStyleSheet("QPushButton\n"
"{\n"
"border:4px solid qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border:10px solid qradialgradient(spread:repeat, cx:0.5, cy:0.5, radius:0.077, fx:0.5, fy:0.5, stop:0 rgba(0, 169, 255, 147), stop:0.497326 rgba(0, 0, 0, 147), stop:1 rgba(0, 169, 255, 147));\n"
"}")
        self.mp3_open_button.setObjectName("mp3_open_button")
        self.stackedWidget.addWidget(self.mp3_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.settings_save_location_line_edit = QtWidgets.QLineEdit(self.settings_page)
        self.settings_save_location_line_edit.setGeometry(QtCore.QRect(20, 70, 621, 51))
        self.settings_save_location_line_edit.setStyleSheet("QLineEdit\n"
"{\n"
"    font: 87 14pt \"Roboto Black\";\n"
"    border-radius:3px;\n"
"border: 1px solid gray;\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"    background-color: rgb(104, 108, 165);\n"
"}")
        self.settings_save_location_line_edit.setObjectName("settings_save_location_line_edit")
        self.settings_save_browse_button = QtWidgets.QPushButton(self.settings_page)
        self.settings_save_browse_button.setGeometry(QtCore.QRect(650, 70, 61, 51))
        self.settings_save_browse_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(56, 58, 89);\n"
"    color: white;\n"
"    border:1px solid qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"    font: 87 14pt \"Roboto Slab Black\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(94, 96, 172);\n"
"}\n"
"")
        self.settings_save_browse_button.setObjectName("settings_save_browse_button")
        self.settings_check_box = QtWidgets.QCheckBox(self.settings_page)
        self.settings_check_box.setGeometry(QtCore.QRect(30, 150, 611, 31))
        self.settings_check_box.setStyleSheet("QCheckBox\n"
"{\n"
"font: 8pt \"Russo One\";\n"
"color: rgb(255, 85, 255);\n"
"}\n"
"")
        self.settings_check_box.setObjectName("settings_check_box")
        self.settings_save_location_mp3_line_edit = QtWidgets.QLineEdit(self.settings_page)
        self.settings_save_location_mp3_line_edit.setGeometry(QtCore.QRect(20, 210, 621, 51))
        self.settings_save_location_mp3_line_edit.setStyleSheet("QLineEdit\n"
"{\n"
"    font: 87 14pt \"Roboto Black\";\n"
"    border-radius:3px;\n"
"border: 1px solid gray;\n"
"}\n"
"QLineEdit:hover\n"
"{\n"
"    background-color: rgb(104, 108, 165);\n"
"}")
        self.settings_save_location_mp3_line_edit.setObjectName("settings_save_location_mp3_line_edit")
        self.settings_mp3_browse_button = QtWidgets.QPushButton(self.settings_page)
        self.settings_mp3_browse_button.setGeometry(QtCore.QRect(650, 210, 61, 51))
        self.settings_mp3_browse_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(56, 58, 89);\n"
"    color: white;\n"
"    border:1px solid qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.05 rgba(14, 8, 73, 255), stop:0.36 rgba(28, 17, 145, 255), stop:0.6 rgba(126, 14, 81, 255), stop:0.75 rgba(234, 11, 11, 255), stop:0.79 rgba(244, 70, 5, 255), stop:0.86 rgba(255, 136, 0, 255), stop:0.935 rgba(239, 236, 55, 255));\n"
"    font: 87 14pt \"Roboto Slab Black\";\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"background-color: rgb(94, 96, 172);\n"
"}\n"
"")
        self.settings_mp3_browse_button.setObjectName("settings_mp3_browse_button")
        self.settigns_combobox = QtWidgets.QComboBox(self.settings_page)
        self.settigns_combobox.setGeometry(QtCore.QRect(20, 290, 231, 22))
        self.settigns_combobox.setStyleSheet("QComboBox\n"
"{\n"
"color:black;\n"
"background:white;\n"
"border:none;\n"
"border-radius: 3px;\n"
"background:rgb(152, 158, 241);\n"
"}\n"
"QComboBox::drop-down {\n"
"    width: 20px;\n"
"    background:rgb(152, 158, 241);\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"\n"
"}")
        self.settigns_combobox.setObjectName("settigns_combobox")
        self.settigns_combobox.addItem("")
        self.settigns_combobox.addItem("")
        self.settigns_combobox.addItem("")
        self.settings_save_button = QtWidgets.QPushButton(self.settings_page)
        self.settings_save_button.setGeometry(QtCore.QRect(30, 370, 201, 41))
        self.settings_save_button.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(170, 85, 255);\n"
"    \n"
"    font: 87 12pt \"Nunito Black\";\n"
"    border-radius:5px;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"    background-color: rgb(211, 139, 255);\n"
"}\n"
"QPushButton:pressed\n"
"{\n"
"    background-color:rgb(109, 54, 163)\n"
"}")
        self.settings_save_button.setObjectName("settings_save_button")
        self.stackedWidget.addWidget(self.settings_page)
        self.frame = QtWidgets.QFrame(self.mainFrame)
        self.frame.setGeometry(QtCore.QRect(10, 29, 41, 491))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.home_icon = QLabelClickable(self.frame)
        self.home_icon.setGeometry(QtCore.QRect(5, 20, 21, 21))
        self.home_icon.setStyleSheet("")
        self.home_icon.setText("")
        self.home_icon.setPixmap(QtGui.QPixmap("Images/home.png"))
        self.home_icon.setScaledContents(True)
        self.home_icon.setObjectName("home_icon")
        self.downloads_icon = QLabelClickable(self.frame)
        self.downloads_icon.setGeometry(QtCore.QRect(-7, 70, 51, 31))
        self.downloads_icon.setText("")
        self.downloads_icon.setPixmap(QtGui.QPixmap("Images/downloads.png"))
        self.downloads_icon.setScaledContents(True)
        self.downloads_icon.setObjectName("downloads_icon")
        self.settings_icon = QLabelClickable(self.frame)
        self.settings_icon.setGeometry(QtCore.QRect(5, 450, 21, 21))
        self.settings_icon.setText("")
        self.settings_icon.setPixmap(QtGui.QPixmap("Images/settings.jpg"))
        self.settings_icon.setScaledContents(True)
        self.settings_icon.setObjectName("settings_icon")
        self.mp3s_icon = QLabelClickable(self.frame)
        self.mp3s_icon.setGeometry(QtCore.QRect(3, 125, 31, 21))
        self.mp3s_icon.setText("")
        self.mp3s_icon.setPixmap(QtGui.QPixmap("Images/mp3.png"))
        self.mp3s_icon.setScaledContents(True)
        self.mp3s_icon.setObjectName("mp3s_icon")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Form)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.quitButton.setText(_translate("Form", "X"))
        self.home_search_line_edit.setPlaceholderText(_translate("Form", "  URL OR VIDEO TITLE"))
        self.home_download_button.setText(_translate("Form", "Download"))
        self.downloads_open_button.setText(_translate("Form", "Open"))
        self.downloads_search_downloads_line_edit.setPlaceholderText(_translate("Form", "Search downloaded songs"))
        self.mp3_file_location_line_edit.setPlaceholderText(_translate("Form", "File Location"))
        self.mp3_save_location_line_edit.setPlaceholderText(_translate("Form", "Save Location"))
        self.convert_button.setText(_translate("Form", "Convert"))
        self.mp3_file_location_browse_button.setText(_translate("Form", "..."))
        self.mp3_save_location_browse_button.setText(_translate("Form", "..."))
        self.mp3_play_button.setText(_translate("Form", "Play"))
        self.mp3_open_button.setText(_translate("Form", "Open"))
        self.settings_save_location_line_edit.setPlaceholderText(_translate("Form", "Save Location for downloaded files"))
        self.settings_save_browse_button.setText(_translate("Form", "..."))
        self.settings_check_box.setText(_translate("Form", "Always convert to mp3 on download"))
        self.settings_save_location_mp3_line_edit.setPlaceholderText(_translate("Form", "Save Location for mp3 files"))
        self.settings_mp3_browse_button.setText(_translate("Form", "..."))
        self.settigns_combobox.setItemText(0, _translate("Form", "Select"))
        self.settigns_combobox.setItemText(1, _translate("Form", "Best"))
        self.settigns_combobox.setItemText(2, _translate("Form", "Worst"))
        self.settings_save_button.setText(_translate("Form", "Save"))